Don't force a build.edn file
liquidz/build.edn pull request #33
Opened 2024-03-25 20:37 UTC by ivarref

Don't force a build.edn file.

The user can store all the config needed in deps.edn if she/he likes.

I also bumped deps-deploy. That also required removing the .alpha for tools.deps usage.

What do you think?

Thanks for a great and user friendly project.

Best regards

2024-04-09 09:51 UTC, ivarref commented
Hi @liquidz 

Did you by any chance have time to look at this?

Thanks and best regards.

2024-04-09 20:58 UTC, liquidz commented
@ivarref Ah sorry. I've overlooked this PR.
I'll have a look!

2024-04-09 22:17 UTC, liquidz requested changes
@ivarref Thanks for your contribution!
Overall the PR looks good :)

> That also required removing the .alpha for tools.deps usage.

Nice catch! Thank you

2024-04-09 22:17 UTC, liquidz commented on src/build_edn/main.clj
> +   [clojure.java.io :as jio]))
Could you use idiomatic namespace aliases?
https://github.com/bbatsov/clojure-style-guide#use-idiomatic-namespace-aliases

```suggestion
   [clojure.java.io :as io]))
```

2024-04-10 09:00 UTC, ivarref commented on src/build_edn/main.clj
> +   [clojure.java.io :as jio]))
Thanks @liquidz , fixed now

2024-04-10 23:09 UTC, liquidz requested changes
@ivarref Sorry, just one last point.
Could you also remove the following `alpha`?

https://github.com/liquidz/build.edn/blob/ab331f5c651dacccc906e2d41cedcbe6b3e6932c/test/build_edn/repository_test.clj#L5

2024-04-11 07:41 UTC, ivarref commented
Fixed test :+1:

2024-04-11 07:55 UTC, liquidz approved these changes
Thank you so much! 
I'll release a new version in this weekend.

2024-04-11 07:55 UTC, merged

2024-04-12 21:25 UTC, liquidz commented
@ivarref Just released v0.11.257 :)

2024-04-13 11:23 UTC, ivarref commented
Thanks a lot @liquidz ❤️ 🧡 💛